local map = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }

map('n', '<Space>bc', '<Cmd>bdelete<CR>', opts)
map('n', '<Space>bl', '<Cmd>BufferLineTogglePin<CR>', opts)
map('n', '<Space>bk', '<Cmd>BufferLinePick<CR>', opts)
map('n', '<Space>bp', '<Cmd>bprevious<CR>', opts)
map('n', '<Space>bn', '<Cmd>bnext<CR>', opts)
map('n', '<A-1>',     '<Cmd>BufferLineGoToBuffer 1<CR>', opts)
map('n', '<A-2>',     '<Cmd>BufferLineGoToBuffer 2<CR>', opts)
map('n', '<A-3>',     '<Cmd>BufferLineGoToBuffer 3<CR>', opts)
map('n', '<A-4>',     '<Cmd>BufferLineGoToBuffer 4<CR>', opts)
map('n', '<A-5>',     '<Cmd>BufferLineGoToBuffer 5<CR>', opts)
map('n', '<A-6>',     '<Cmd>BufferLineGoToBuffer 6<CR>', opts)
map('n', '<A-7>',     '<Cmd>BufferLineGoToBuffer 7<CR>', opts)
map('n', '<A-8>',     '<Cmd>BufferLineGoToBuffer 8<CR>', opts)
map('n', '<A-9>',     '<Cmd>BufferLineGoToBuffer 9<CR>', opts)
map('n', '<A-0>',     '<Cmd>blast<CR>', opts)
map('n', '<Space>b1', '<Cmd>BufferLineGoToBuffer 1<CR>', opts)
map('n', '<Space>b2', '<Cmd>BufferLineGoToBuffer 2<CR>', opts)
map('n', '<Space>b3', '<Cmd>BufferLineGoToBuffer 3<CR>', opts)
map('n', '<Space>b4', '<Cmd>BufferLineGoToBuffer 4<CR>', opts)
map('n', '<Space>b5', '<Cmd>BufferLineGoToBuffer 5<CR>', opts)
map('n', '<Space>b6', '<Cmd>BufferLineGoToBuffer 6<CR>', opts)
map('n', '<Space>b7', '<Cmd>BufferLineGoToBuffer 7<CR>', opts)
map('n', '<Space>b8', '<Cmd>BufferLineGoToBuffer 8<CR>', opts)
map('n', '<Space>b9', '<Cmd>BufferLineGoToBuffer 9<CR>', opts)
map('n', '<Space>b0', '<Cmd>blast<CR>', opts)

map('n', '<Space>e', '<Cmd>NvimTreeToggle<CR>', opts)

map('n', '<Space>ff', '<Cmd>Telescope find_files prompt_prefix=🔍<CR>', opts)
map('n', '<Space>fg', '<Cmd>Telescope live_grep prompt_prefix=🔍<CR>', opts)
map('n', '<Space>fb', '<Cmd>Telescope buffers<CR>', opts)
map('n', '<Space>fh', '<Cmd>Telescope help_tags<CR>', opts)
map('n', '<Space>ft', '<Cmd>TodoTelescope<CR>', opts)

map('n', '<Space>tt', '<Cmd>ToggleTerm<CR>', opts)
map('n', '<Space>tf', '<Cmd>ToggleTerm direction=float<CR>', opts)
map('n', '<Space>tb', '<Cmd>ToggleTerm direction=tab<CR>', opts)
map('n', '<Space>tr', '<Cmd>TroubleToggle<CR>', opts)

map('n', '[d', '<Cmd>lua vim.diagnostic.goto_prev()<CR>', opts)
map('n', ']d', '<Cmd>lua vim.diagnostic.goto_next()<CR>', opts)

map('n', '<Space>lf', '<Cmd>lua vim.diagnostic.open_float()<CR>', opts)
map('n', '<Space>ll', '<Cmd>lua vim.diagnostic.setloclist()<CR>', opts)

map('n', '<F2>', '<Cmd>lua require("renamer").rename()<CR>', opts)
map('n', '<F3>', '<Cmd>Telescope lsp_references<CR>', opts)
map('n', '<F4>', '<Cmd>CMake configure<CR>', opts)
map('n', '<F5>', '<Cmd>CMake build_and_debug<CR>', opts)
map('n', '<C-F5>', '<Cmd>DapContinue<CR>', opts)
map('n', '<F8>', '<Cmd>DapToggleBreakpoint<CR>', opts)
map('n', '<F9>', '<Cmd>DapStepInto<CR>', opts)
map('n', '<F10>', '<Cmd>DapStepOut<CR>', opts)
map('n', '<F11>', '<Cmd>DapStepOver<CR>', opts)
map('n', '<F12>', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)

map('n', 'gf', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
map('n', 'gd', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
map('n', 'gs', '<Cmd>Telescope lsp_document_symbols<CR>', opts)
map('n', 'gr', '<Cmd>Telescope lsp_references<CR>', opts)
map('n', 'gh', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
map('n', 'gi', '<Cmd>lua vim.lsp.buf.implementation()<CR>', opts)
map('n', 'gl', '<Cmd>LazyGit<CR>', opts)
map('n', 'ga', '<Cmd>lua vim.lsp.buf.code_action()<CR>', opts)
map('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)

map('v', '<Space>f', '<Esc><Cmd>lua vim.lsp.buf.range_formatting()<CR>', opts)

